version: '3.4'

services:
  productapi:
    container_name: productapi
    image: ${DOCKER_REGISTRY-}productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5080:80"
    networks:
      - retailerNetwork
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    depends_on:
      - rabbitmq
  
  productapi-daprd:
    image: "daprio/daprd:edge"
    container_name: productapi-daprd
    command: ["./daprd",
              "-app-id", "productapi",
              "-app-port", "80",
              "-placement-host-address", "dapr-placement:50000",
              "-components-path", "/components",
              "-log-level", "debug"]
    volumes:
      - "./components/:/components"
    network_mode: "service:productapi"
    depends_on:
      - productapi

  orderapi:
    container_name: orderapi
    image: ${DOCKER_REGISTRY-}orderapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7080:80"
    networks:
      - retailerNetwork
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    depends_on:
      - rabbitmq
  
  orderapi-daprd:
    image: "daprio/daprd:edge"
    container_name: orderapi-daprd
    command: ["./daprd",
              "-app-id", "orderapi",
              "-app-port", "80",
              "-placement-host-address", "dapr-placement:50000",
              "-components-path", "/components",
              "-log-level", "debug"
    ]
    volumes:
        - "./components/:/components"
    network_mode: "service:orderapi"
    depends_on:
      - orderapi

  customerapi:
    container_name: customerapi
    image: ${DOCKER_REGISTRY-}customerapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6080:80"
    networks:
      - retailerNetwork
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
    depends_on:
      - rabbitmq
  
  customerapi-daprd:
    image: "daprio/daprd:edge"
    container_name: customerapi-daprd
    command: ["./daprd",
              "-app-id", "customerapi",
              "-app-port", "80",
              "-placement-host-address", "dapr-placement:50000",
              "-components-path", "/components",
              "-log-level", "debug"]
    volumes:
        - "./components/:/components"
    network_mode: "service:customerapi"
    depends_on:
      - customerapi

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - retailerNetwork
    ports:
      - "5672:5672"
      - "15673:15672"
  
  dapr-placement:
    image: "daprio/dapr:edge"
    container_name: dapr-placement
    command: ["./placement",
              "-port", "50000",
              "-log-level", "debug"]
    networks:
      - retailerNetwork

networks:
  retailerNetwork: