version: '3.4'

services:
  productapi:
    image: kjel0393/productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5080-5090:80"
    networks:
      - retailerNetwork
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - rabbitmq

  orderapi:
    image: kjel0393/orderapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7080-7090:80"
    networks:
      - retailerNetwork
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - rabbitmq

  customerapi:
    image: kjel0393/customerapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6080-6090:80"
    networks:
      - retailerNetwork
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - rabbitmq

  userapi:
    image: kjel0393/userapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4080-4090:80"
    networks:
      - retailerNetwork
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    deploy:
      replicas: 2
      
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - "8085:8085"
    networks:
      - retailerNetwork
    
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - retailerNetwork
    ports:
      - "5672:5672"
      - "15673:15672"

networks:
  retailerNetwork:
    
volumes:
  featurehub-h2-data: